const BibleBooks: Record<string, string[]> = {
  Genesis: ["genesis", "gen"],
  Exodus: ["exodus", "exo"],
  Leviticus: ["leviticus", "lev"],
  Numbers: ["numbers", "num"],
  Deuteronomy: ["deuteronomy", "deut"],
  Joshua: ["joshua", "josh"],
  Judges: ["judges", "judg", "jud"],
  Ruth: ["ruth"],
  "1 Samuel": ["1samuel", "1sam"],
  "2 Samuel": ["2samuel", "2sam"],
  "1 Kings": ["1kings", "1kgs"],
  "2 Kings": ["2kings", "2kgs"],
  "1 Chronicles": ["1chronicles", "1chr"],
  "2 Chronicles": ["2chronicles", "2chr"],
  Ezra: ["ezra", "ezra"],
  Nehemiah: ["nehemiah", "neh"],
  Esther: ["esther", "esth", "est"],
  Job: ["job", "job"],
  Psalms: ["psalms", "ps"],
  Proverbs: ["proverbs", "prov"],
  Ecclesiastes: ["ecclesiastes", "eccl"],
  "Song of Solomon": ["song of solomon", "song"],
  Isaiah: ["isaiah", "isa"],
  Jeremiah: ["jeremiah", "jer"],
  Lamentations: ["lamentations", "lam"],
  Ezekiel: ["ezekiel", "ezek"],
  Daniel: ["daniel", "dan"],
  Hosea: ["hosea", "hos"],
  Joel: ["joel", "jl"],
  Amos: ["amos"],
  Obadiah: ["obadiah", "obad"],
  Jonah: ["jonah", "jon"],
  Micah: ["micah", "mic"],
  Nahum: ["nahum", "nah"],
  Habakkuk: ["habakkuk", "hab"],
  Zephaniah: ["zephaniah", "zeph"],
  Haggai: ["haggai", "hag"],
  Zechariah: ["zechariah", "zech"],
  Malachi: ["malachi", "mal"],
  Matthew: ["matthew", "matt"],
  Mark: ["mark", "mk"],
  Luke: ["luke", "lk"],
  John: ["john", "jn"],
  Acts: ["acts"],
  Romans: ["romans", "rom"],
  "1 Corinthians": ["1corinthians", "1cor"],
  "2 Corinthians": ["2corinthians", "2cor"],
  Galatians: ["galatians", "gal"],
  Ephesians: ["ephesians", "eph"],
  Philippians: ["philippians", "phil"],
  Colossians: ["colossians", "col"],
  "1 Thessalonians": ["1thessalonians", "1thess"],
  "2 Thessalonians": ["2thessalonians", "2thess"],
  "1 Timothy": ["1timothy", "1tim"],
  "2 Timothy": ["2timothy", "2tim"],
  Titus: ["titus", "tit"],
  Philemon: ["philemon", "philem"],
  Hebrews: ["hebrews", "heb"],
  James: ["james", "js"],
  "1 Peter": ["1peter", "1pet"],
  "2 Peter": ["2peter", "2pet"],
  "1 John": ["1john", "1jn"],
  "2 John": ["2john", "2jn"],
  "3 John": ["3john", "3jn"],
  Jude: ["jude", "jd"],
  Revelation: ["revelation", "rev"],
};

export default BibleBooks;
